# Generated by Django 2.2 on 2019-04-16 11:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=20)),
                ('sslc_percent', models.IntegerField(default=50)),
                ('pu_percent', models.IntegerField(default=50)),
                ('degree', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('aggregate', models.FloatField(default=5.5)),
                ('about_me', models.TextField()),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('who_can_apply', models.TextField()),
                ('salary', models.IntegerField(default=1000)),
                ('skills_req', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('apply_by', models.DateField(auto_now=True)),
                ('vacancy', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1)),
                ('candidate', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Candidate')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.JobPosting')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, 'RECRUITER'), (2, 'STUDENT')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_name', models.CharField(max_length=100)),
                ('about_company', models.TextField()),
                ('admin_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organisation'),
        ),
    ]
