# Generated by Django 2.1.7 on 2019-03-10 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='rec_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='food.Food'),
        ),
    ]
