# Generated by Django 2.1.7 on 2019-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_recipes_rec_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='procedure',
            field=models.FileField(upload_to='food/procedure/'),
        ),
    ]
