# Generated by Django 2.1.5 on 2019-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20190310_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rec_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
